# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0006_taskworker_thanked'),
        ('crowdsourcing', '0007_auto_20170817_2207'),
    ]

    operations = [
    ]
