# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0008_merge_20170822_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thanked_count',
            field=models.IntegerField(default=0),
        ),
    ]
