# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0009_project_thanked_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thanked_count',
        ),
    ]
